CREATE TABLE "homework-tracker_account" (
	"userId" varchar(255) NOT NULL,
	"type" varchar(255) NOT NULL,
	"provider" varchar(255) NOT NULL,
	"providerAccountId" varchar(255) NOT NULL,
	"refresh_token" text,
	"access_token" text,
	"expires_at" integer,
	"token_type" varchar(255),
	"scope" varchar(255),
	"id_token" text,
	"session_state" varchar(255),
	CONSTRAINT "homework-tracker_account_provider_providerAccountId_pk" PRIMARY KEY("provider","providerAccountId")
);
--> statement-breakpoint
CREATE TABLE "homework-tracker_book" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "homework-tracker_book_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"title" varchar(255) NOT NULL,
	"userId" varchar(255) NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "homework-tracker_session" (
	"sessionToken" varchar(255) PRIMARY KEY NOT NULL,
	"userId" varchar(255) NOT NULL,
	"expires" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "homework-tracker_task_part" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "homework-tracker_task_part_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"taskId" integer NOT NULL,
	"letter" varchar(2) NOT NULL,
	"completed" boolean DEFAULT false NOT NULL
);
--> statement-breakpoint
CREATE TABLE "homework-tracker_task" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "homework-tracker_task_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"unitId" integer NOT NULL,
	"number" integer NOT NULL,
	"completed" boolean DEFAULT false NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "homework-tracker_unit" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "homework-tracker_unit_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"bookId" integer NOT NULL,
	"title" varchar(255) NOT NULL,
	"number" integer NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "homework-tracker_user" (
	"id" varchar(255) PRIMARY KEY NOT NULL,
	"name" varchar(255),
	"email" varchar(255) NOT NULL,
	"emailVerified" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
	"image" varchar(255)
);
--> statement-breakpoint
CREATE TABLE "homework-tracker_verification_token" (
	"identifier" varchar(255) NOT NULL,
	"token" varchar(255) NOT NULL,
	"expires" timestamp with time zone NOT NULL,
	CONSTRAINT "homework-tracker_verification_token_identifier_token_pk" PRIMARY KEY("identifier","token")
);
--> statement-breakpoint
ALTER TABLE "homework-tracker_account" ADD CONSTRAINT "homework-tracker_account_userId_homework-tracker_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."homework-tracker_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "homework-tracker_book" ADD CONSTRAINT "homework-tracker_book_userId_homework-tracker_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."homework-tracker_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "homework-tracker_session" ADD CONSTRAINT "homework-tracker_session_userId_homework-tracker_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."homework-tracker_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "homework-tracker_task_part" ADD CONSTRAINT "homework-tracker_task_part_taskId_homework-tracker_task_id_fk" FOREIGN KEY ("taskId") REFERENCES "public"."homework-tracker_task"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "homework-tracker_task" ADD CONSTRAINT "homework-tracker_task_unitId_homework-tracker_unit_id_fk" FOREIGN KEY ("unitId") REFERENCES "public"."homework-tracker_unit"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "homework-tracker_unit" ADD CONSTRAINT "homework-tracker_unit_bookId_homework-tracker_book_id_fk" FOREIGN KEY ("bookId") REFERENCES "public"."homework-tracker_book"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "account_user_id_idx" ON "homework-tracker_account" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "book_user_id_idx" ON "homework-tracker_book" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "t_user_id_idx" ON "homework-tracker_session" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "task_part_task_id_idx" ON "homework-tracker_task_part" USING btree ("taskId");--> statement-breakpoint
CREATE INDEX "task_unit_id_idx" ON "homework-tracker_task" USING btree ("unitId");--> statement-breakpoint
CREATE INDEX "unit_book_id_idx" ON "homework-tracker_unit" USING btree ("bookId");